- hosts: all
  sudo: true
  vars:
    install_dir: "/opt/dot-jenkins"
  tasks:
    - name: Disable power management for Edimax WLAN dongle
      copy: src=../etc/8192cu.conf dest=/etc/modprobe.d/8192cu.conf

    - name: Ensure install directory exists
      file: name={{ install_dir }} state=directory

    - name: Copy stuff
      copy: src={{ item }} dest={{ install_dir }}
      with_fileglob:
        - ../*.py

    - name: Set executable bit on Python entrypoint
      file: name={{ install_dir }}/controller.py state=file mode=a+rx

    - name: Install configuration
      template: src={{ controller_config }} dest=/etc/dot-jenkins.cfg

    - name: Ensure needed Python libs are present
      pip: name=requests state=present

    - name: Ensure supervisor package is installed
      apt: name=supervisor state=present

    - name: Install supervisord.conf
      template: src=../etc/supervisord.conf dest=/etc/supervisor/conf.d/dot-jenkins-supervisord.conf

    - name: Restart supervisord
      service: name=supervisor state=restarted
